FROM nginx:stable-alpine
COPY dist/ /usr/share/nginx/html/admin
COPY nginx.admin.conf /etc/nginx/conf.d/default.conf
COPY dist/config.json /config/config.json
CMD envsubst < /config/config.json > /usr/share/nginx/html/admin/config.json && \
  exec nginx -g 'daemon off;'
